### ISSUE TITLE
Zork not installable, jzip fails

### ISSUE THREAD

**Issue by du5tball** [wjwwood/homebrew-zork#6]
→ brew install zork1
==> Installing zork1 from wjwwood/zork
==> Installing dependencies for wjwwood/zork/zork1: jzip
==> Installing wjwwood/zork/zork1 dependency: jzip
==> Downloading http://download.sourceforge.net/jzip/jzip21-10oct2000.zip
Already downloaded: /Users/ssonne/Library/Caches/Homebrew/jzip-2.1.zip
==> Patching
patching file osdepend.c
==> make -f unixio.mak
Last 15 lines from /Users/ssonne/Library/Logs/Homebrew/jzip/01.make:
          ((g)->have ? ((g)->have--, (g)->pos++, *((g)->next)++) : gzgetc(g))
                        ~~~^ ~~~~
fileio.c:123:35: error: member reference base type 'gzFile' (aka 'struct gzFile_s *') is not a structure or union
         story_offset += 65536L * jz_getc( gfp );
                                  ^~~~~~~~~~~~~~
./ztypes.h:84:20: note: expanded from macro 'jz_getc'
#define jz_getc    gzgetc
                   ^
/usr/include/zlib.h:1699:41: note: expanded from macro 'gzgetc'
          ((g)->have ? ((g)->have--, (g)->pos++, *((g)->next)++) : gzgetc(g))
                                     ~~~^ ~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [fileio.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by tweissin** [comment]
+1
